### ISSUE TITLE
No batch execution in Linux

### ISSUE THREAD

**Issue by stefankinell** [karttapullautin/karttapullautin#17]
I can not get batch mode to work on Linux. It just states "Starting thread 1" and counts up to the right number of threads, and then close the script.

**Comment by jaluzdi** [comment]
I do have the same problem in Ubuntu Linux 22.04
I tweaked pullauta.ini to run 4 processes
I created "in" folder where I put 24 *.laz files
I created "out" folder
I executed an sh script to run pullauta. The contecnt of the sh script is:

echo Start - `date "+%Y-%m-%d %H:%M:%S.%3N"` > rusty-pullauta.log
perl pullauta >> rusty-pullauta.log 2>&1
echo Finish - `date "+%Y-%m-%d %H:%M:%S.%3N"` >> rusty-pullauta.log

And the rusty-pullauta.log i get the following content:

Start - 2023-04-12 16:30:33.918
Karttapullautin v. 20190203 (c) Jarkko Ryyppo 2012-19  All rights reserved.
This exe is free for non commercial use or if used for for navsport 
mapping (orienteering, rogaining, adventure racing mapping).
There is no warranty. Use it at your own risk!
This is rusty karttapulatin... There is no warranty. Use it at your own risk!

Starting thread 1
Starting thread 2
Starting thread 3
Starting thread 4
Finish - 2023-04-12 16:30:34.613

**Comment by jaluzdi** [comment]
I do get the same result


`juantxo@Intel-NUC10i5FNH:~$ /usr/bin/perl -v`

`This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)`

`Copyright 1987-2021, Larry Wall`

`Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.`

`Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.`



`juantxo@Intel-NUC10i5FNH:~$ /usr/bin/env perl -v`

`This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-gnu-thread-multi
(with 57 registered patches, see perl -V for more detail)`

`Copyright 1987-2021, Larry Wall`

`Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.`

`Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.`

**Comment by jaluzdi** [comment]
pullauta is an executable

`juantxo@Intel-NUC10i5FNH:~/rusty-pullauta$ ./pullauta`
`Karttapullautin v. 20190203 (c) Jarkko Ryyppo 2012-19  All rights reserved.`
`This exe is free for non commercial use or if used for for navsport `
`mapping (orienteering, rogaining, adventure racing mapping).`
`There is no warranty. Use it at your own risk!`

`USAGE:`
`pullauta [parameter 1] [parameter 2] [parameter 3] ... [parameter n]`
`See readme.txt for more details`

And listing the files it has the execution permission

`juantxo@Intel-NUC10i5FNH:~/rusty-pullauta$ ll pulla* `
`-rwxrwxr-x 1 juantxo juantxo   340084 abr 12 17:23 pullauta* `
`-rw-rw-r-- 1 juantxo juantxo 10191744 abr 12 17:23 pullauta.exe `
`-rw-rw-r-- 1 juantxo juantxo     7141 abr 12 17:23 pullauta.ini `
`-rwxrwxr-x 1 juantxo juantxo   351206 abr 12 17:23 pullauta.pl* `

**Comment by jaluzdi** [comment]
Thank you very much @rphlo 
It works nows. Great !!!
I had 24 *.laz files in my **in** folder
And now I have 96 files in my **out** folder (48 *.png + 48 *.pgw)
And I have the 24 temp folders with *.xyz, *.dxf, *.png, *.txt files

**Comment by stefankinell** [comment]
My lazlist1.txt and so on are empty, and script ending after having written out dir *.laz and creating empty laslist-files.

I have tried changing names of in-folder as well. Both direct links and relative.

**Comment by stefankinell** [comment]
Forget my last comment. My time to have brain freeze. Now I am running 24 parallel threds on Linux. This is going to be interesting to watch. Well, at least the result of speed, perhaps not the output windows :-D

Thanks @rphlo  and welcome @jaluzdi - good to have more people testing since I also realize I do not use all parts of the software.
